from django.contrib import admin
from .models import AutomationRule, AutomationRun, IntakeQuestion, IntakeResponse, Milestone, PaymentInstallment, Project, ProjectActivity, ProjectComment, ProjectFile, ProjectInvitation, Proposal, ProposalItem, SavedWorkView, ServiceInquiry, ServiceOffering, Task, WorkflowStage, WorkOccurrence, WorkTemplate
admin.site.register(Project)
admin.site.register(Task)
admin.site.register(Milestone)
admin.site.register(ProjectComment)
admin.site.register(WorkTemplate)
admin.site.register(IntakeQuestion)
admin.site.register(IntakeResponse)
admin.site.register(AutomationRule)
admin.site.register(AutomationRun)
admin.site.register(Proposal)
admin.site.register(WorkOccurrence)
admin.site.register(SavedWorkView)
admin.site.register(PaymentInstallment)
admin.site.register(ProposalItem)
admin.site.register(WorkflowStage)
admin.site.register(ServiceOffering)
admin.site.register(ServiceInquiry)
admin.site.register(ProjectFile)
admin.site.register(ProjectInvitation)
admin.site.register(ProjectActivity)
