# Generated by Django 5.2.5 on 2026-08-23 07:56

from django.db import migrations, models


def preserve_completed_milestones(apps, schema_editor):
    Milestone = apps.get_model('projects', 'Milestone')
    Milestone.objects.filter(completed=True).update(review_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='review_status',
            field=models.CharField(choices=[('draft', 'In progress'), ('submitted', 'Awaiting review'), ('changes', 'Changes requested'), ('approved', 'Approved')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_completed_milestones, migrations.RunPython.noop),
    ]
